### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by fabianschilling** [lis-epfl/HRI_communication#1]
You definitely need a `.gitignore`: I'm seeing way too many `.pyc`, `__pycache__`, and `.ipynb_checkpoints` ;)

**Comment by jlecoeur** [comment]
Very true.
BTW how can we disable notifications for all new projects under the lis-epfl organisation?

**Comment by medioman22** [comment]
@fabianschilling thanks mate!

**Comment by medioman22** [comment]
@jlecoeur 
no idea, especially since I don't get most of them :)
should I use my private account?

**Comment by jlecoeur** [comment]
No no it is better to use this account. And I can happily ignore the
notifications. I am more asking for the people who might get annoyed by the
notifications, or others who would like to have semi-privacy in their
project: you do not want to inform the whole lab each time you submit an
issue or a pull request.
Let's ask Olex to have a look at this.

Le jeu. 30 août 2018 à 15:57, Matteo Macchini <notifications@github.com> a
écrit :

**Comment by medioman22** [comment]
let's keet the issue open until we have a solution for the notifications

**Comment by fabianschilling** [comment]
Fixed by https://github.com/lis-epfl/HRI_communication/pull/3
